name: CI Pipeline with Unit, Integration, and Regression Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip python -m pip install -r requirements.txt
      - name: Run Unit Tests
        run: pytest tests/test_unit.py --maxfail=1 --disable-warnings -q

      - name: Run Integration Tests
        run: pytest tests/test_integration.py --maxfail=1 --disable-warnings -q

      - name: Run Regression Tests
        run: pytest tests/test_regression.py --maxfail=1 --disable-warnings -q
